Sw 102
Trimesteret/AngGUI pull request #15
Opened 2023-11-27 12:03 UTC by DaniekFjaes

![image_2023-11-27_125859353](https://github.com/Trimesteret/AngGUI/assets/79269401/8b1c02ed-c08d-4295-baa3-dc31166818a4)

Still W.I.P and has a few issues:
- Needs some specific formatting for lower resolutions, right now it looks subpar
- Missing the ability to change quantity on basket items
- Basket items are currently just a placeholder, until someone actually makes the basket site
- Needs to give a warning when incorrect information is entered.
- Price isn't calculated because it should (probably?) be fetched from a service

2023-11-28 14:50 UTC, Thekid2002 requested changes

2023-11-28 14:50 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
>    checkoutForm = new FormGroup({
Use formbuilder

2023-11-28 14:50 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
> +  addressFields = [
Use wizard service : OR remove 🗡️

2023-11-28 14:50 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
> +      if (!isNaN(itemPrice)) {
Hent pris fra API <3

2023-11-28 14:50 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.html
> +  <div fxLayout = "row" fxFlexFill>
No space in equal

2023-12-04 13:50 UTC, DaniekFjaes commented on src/app/webshop/checkout/checkout.component.ts
> +      if (!isNaN(itemPrice)) {
Jeg får vel itemDTOs fra basket, så giver det mening at hente priserne igen, når jeg allerede (burde) have dem?

2023-12-05 09:12 UTC, Thekid2002 requested changes

2023-12-05 09:12 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
> +  basketContent = [
DEn skal hentes fra orderservice

2023-12-05 09:12 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
> +    console.log(this.checkoutForm);
We do not console.log in production code (unless errors) <3

2023-12-05 09:12 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
> +      // Example: 'name': [initialValue, [validators]]
Remove comments

2023-12-05 09:12 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
>    createCheckout():void{
Add spacing and comments + should be public

2023-12-05 09:12 UTC, Thekid2002 commented on src/app/webshop/checkout/checkout.component.ts
> +  goToPayment():void{
Add spacing and comment + should be public

2023-12-09 12:54 UTC, Thekid2002 approved these changes

2023-12-09 12:54 UTC, merged